### ISSUE TITLE
Crash after upgrading to 2.0.x

### ISSUE THREAD

**Issue by GrahamBorland** [castle/castle-android#40]
Getting a crash after upgrading from 1.2.2 to 2.0.1.

```
    Caused by: java.lang.UnsupportedOperationException: Tried to obtain display from a Context not associated with one. Only visual Contexts (such as Activity or one created with Context#createWindowContext) or ones created with Context#createDisplayContext are associated with displays. Other types of Contexts are typically related to background entities and may return an arbitrary display.
        at android.app.ContextImpl.getDisplay(ContextImpl.java:2489)
        at android.content.ContextWrapper.getDisplay(ContextWrapper.java:1004)
        at io.castle.android.highwind.Highwind.token(SourceFile:20)
        at io.castle.android.Castle.id(Castle.java:95)
        at io.castle.android.Castle.clientId(Castle.java:298)
        at io.castle.android.api.model.Context.init(Context.java:25)
        at io.castle.android.api.model.Context.create(Context.java:30)
        at io.castle.android.Castle.createContext(Castle.java:458)
        at io.castle.android.api.model.Event.<init>(Event.java:41)
        at io.castle.android.Castle.track(Castle.java:167)
        at io.castle.android.Castle.registerLifeCycleCallbacks(Castle.java:79)
        at io.castle.android.Castle.configure(Castle.java:121)
        at ynab.app.application.App.onCreate(App.kt:172)
```
Relevant line is
```
        Castle.configure(
            this,    // application
            getString(R.string.castle_publishable_key)
        )
```

The changelog for releases 2.0.0 and 2.0.1 doesn't contain any helpful information about what's changed since 1.2.x, which is surprising for a major-version release; I don't know if we're supposed to change the way we initialise the Castle SDK? The changelog mentions adding Highwind, but I don't know what the implications of this are for users of the SDK.

**Comment by sebastiansimson** [comment]
Thank you for reporting this. As you said the release notes were not very helpful. I have updated them now to be more descriptive of the changes. 

What has changes is that we introduced new device parameters and improved the collection of existing parameters.

The crash issue is a bug in the implementation for getting screen size on Android 11, we have a fix in place for this and will release a new version later today

**Comment by parthjshah95** [comment]
@sebastiansimson I am facing the same issue in my other app. Could you please let me know how you fixed this? The commit you have referenced here simply upgrades the version of the "highwind" dependency.
Did you find a workaround for the android 11 bug to get screenSize?

Thanks in advance, would be a big help for me!
