### ISSUE TITLE
Instant Crashes with 3.0.1

### ISSUE THREAD

**Issue by bparent** [castle/castle-android#56]
Hello,

Using castle 3.0.1 we saw an alarming number of crashes with this stack trace:

```
Fatal Exception: java.lang.NoSuchMethodError: No virtual method sliceByValue([Ljava/lang/Double;D)[Ljava/lang/Object; in class Lio/castle/highwind/android/l; or its super classes (declaration of 'io.castle.highwind.android.l' appears in /data/app/~~ksiqhsb-ZkUqkhARTSiMwQ==/com.app-wSmrcaeNcR_t7LzOXNyVpg==/base.apk!classes4.dex)
       at io.castle.highwind.android.h$a.a(h.java:18)
       at io.castle.highwind.android.d.a(d.java:93)
       at io.castle.highwind.android.Highwind.token(Highwind.java:8)
       at io.castle.android.Castle.id(Castle.java:109)
       at io.castle.android.Castle.createRequestToken(Castle.java:273)
       at io.castle.android.api.model.Event.<init>(Event.java:38)
       at io.castle.android.api.model.CustomEvent.<init>(CustomEvent.java:31)
       at io.castle.android.api.model.CustomEvent.<init>(CustomEvent.java:22)
       at io.castle.android.Castle.custom(Castle.java:181)
       at io.castle.android.Castle.registerLifeCycleCallbacks(Castle.java:93)
       at io.castle.android.Castle.configure(Castle.java:148)
       at com.app.app.Application$initializeCastle$1.invokeSuspend(Application.kt:373)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```       

We are launching Castle like so:
```
    GlobalScope.launch(dispatchers.io) {
      val config = CastleConfiguration.Builder()
          .debugLoggingEnabled(BuildConfig.DEBUG)
          .screenTrackingEnabled(true)
          .build()

      Castle.configure(this@Application,castlePublishableApiKey, config)
    }
```

**Comment by GrahamBorland** [comment]
Also in 3.0.2

**Comment by GrahamBorland** [comment]
Crashes instantly on app startup. I'm not sure what triggers it, but once it starts, it happens every time on app launch until a subsequent uninstall/reinstall of the app.

**Comment by GrahamBorland** [comment]
We see the crash with 3.0.1 and 3.0.2, but *not* 3.0.0. So I guess we can downgrade to 3.0.0 while we await the fix.

**Comment by sebastiansimson** [comment]
Thank you for reporting this and sorry about the delayed feedback. 

It seems like it tries to get the un-obfuscated version of one of our internal methods. This was introduced in version 2.0.0 of the SDKs so it would seem that there is some issue introduced in the obfuscation for the 3.0.1 release. 

I will investigate what the reason could be and keep the issue updated with the progress.

**Comment by sebastiansimson** [comment]
We now have a fix for the issue that resulted in the incorrectly obfuscated code that in turn resulted in the crash.
We will release a new version of the SDK with the fix in the coming days.
