### ISSUE TITLE
Strange GPS crash with 3.0.0

### ISSUE THREAD

**Issue by bparent** [castle/castle-android#57]
I don't know how serious this is, but we had 1 person run into a lot of crashes:

```
Fatal Exception: java.lang.SecurityException: "gps" location provider requires ACCESS_FINE_LOCATION permission.
       at android.os.Parcel.readException(Parcel.java:2029)
       at android.os.Parcel.readException(Parcel.java:1975)
       at android.location.ILocationManager$Stub$Proxy.getLastLocation(ILocationManager.java:863)
       at android.location.LocationManager.getLastKnownLocation(LocationManager.java:1305)
       at io.castle.android.highwind.Highwind.token(Highwind.java:5)
       at io.castle.android.Castle.id(Castle.java:96)
       at io.castle.android.Castle.createRequestToken(Castle.java:306)
       at io.castle.android.api.model.Context.init(Context.java:25)
       at io.castle.android.api.model.Context.create(Context.java:30)
       at io.castle.android.Castle.createContext(Castle.java:462)
       at io.castle.android.api.model.Event.<init>(Event.java:41)
       at io.castle.android.Castle.track(Castle.java:168)
       at io.castle.android.Castle.registerLifeCycleCallbacks(Castle.java:82)
       at io.castle.android.Castle.configure(Castle.java:135)
       at com.app.app.Application$initializeCastle$1.invokeSuspend(Application.kt:373)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```       

Our app doesn't request this permission, so we wanted to make sure that castle wasn't requesting it for some reason.

**Comment by sebastiansimson** [comment]
Thank you for reporting this and sorry for the delayed feedback. The SDK collects location information if the host app has already requested location permission and the user approved it.

Unfortunately it seems like there is a bug in the logic for the permission guards on our end. 

I will work on fixing this and update this issue with the progress.

**Comment by sebastiansimson** [comment]
I have now created a fix for the permission logic in one of our internal libraries that resulted in the crash.
We will release a new version of the SDK with the fix in the coming days.
